mqtt-subscriber-griddb-client:
  build: mqtt-subscriber-griddb-client
  restart: always
  command: python3 mqtt-sub-griddb-c.py
  environment:
        - HOST_IP=${HOSTNAME}

rest-ws:
  build: rest-ws
  restart: always
  ports:
   - 80:80
  command: python3 rest-ws.py

grafana-ws:
  build: grafana-ws
  restart: always
  ports:
   - 8081:8081
  command: python3 grafana-ws.py

cadvisor:
  image: google/cadvisor:latest
  ports:
   - 8080:8080
  volumes:
    - /:/rootfs:ro
    - /var/run:/var/run:rw
    - /sys:/sys:ro
    - /var/lib/docker/:/var/lib/docker:ro